name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Install termcheck
      run: go get github.com/Keyl0ve/termcheck@latest

    - name: check which
      run: which termcheck

    - name: Go vet
      run: go vet -vettool=($which termcheck) ./...
